{% set version = "2.4.3" %}

package:
  name: tensorflow-split
  version: {{ version }}

source:
  url: https://github.com/tensorflow/tensorflow/archive/v{{ version }}.tar.gz
  sha256: cafd520c753f8755a9eb1262932f685dc722d8658f08373f8ec88d8acd58d7d4

  patches:
    - patches/0001-relax-tolerence-in-special_math_test.patch
    - patches/0002-skip-read-only-debugger_cli_common-test.patch
    - patches/0003-relax-precision-in-matrix_log_op_test.patch
    # requires setting GRPCIO_VERSION in build script
    - patches/0004-loosen-requirements.patch
    - patches/0005-osx-arm64.patch  # [osx and arm64]

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy 1.19.*                           # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # see https://github.com/tensorflow/tensorflow/blob/v{{ version }}/.bazelversion
    - bazel 3.1.0  # [not osx]
    # For osx-arm64 cross-compilation to work, we need bazel>=4.1
    - bazel 4.0  # [osx]
    - grpc-cpp
    - libprotobuf
    - nasm
    - sed
  host:
    # conda build requirements
    - python
    - pip
    - zlib
    - libpng
    - libcurl
    - curl         # [win]
    - unzip        # [not win]
    - zip          # [not win]
    - m2-unzip     # [win]
    - m2-zip       # [win]
    - openjdk >=8
    - nsync
    # TF_SYSTEM_LIBS
    - astor >=0.7.1
    - cython >=0.28.4
    - dill >=0.3.1.1
    - giflib
    - grpc-cpp
    - flatbuffers
    - icu
    - jpeg
    - libpng
    - libprotobuf
    - openssl
    - pybind11
    - sqlite
    - snappy
    - zlib
    # requirements specified by the package itself, see
    # github.com/tensorflow/tensorflow/blob/v{{ version }}/tensorflow/tools/pip_package/setup.py
    - absl-py >=0.10.0
    - astunparse >=1.6.3
    - python-flatbuffers 1.12.*
    - google-pasta >=0.2
    - h5py >=2.10
    - keras-preprocessing >=1.1.2
    - numpy 1.19.*
    - opt_einsum 3.3.0.*
    - protobuf >=3.9.2
    - six 1.15.0.*
    - termcolor >=1.1.0
    - typing_extensions 3.7.4.*
    - wheel >=0.35
    - wrapt >=1.11.1
    # upstream wants exact pin for gast
    - gast ==0.3.3
    # TF-API needs to move in sync
    - tensorboard >=2.4.0,<2.5
    - tensorflow-estimator >=2.4.0,<2.5

outputs:
  - name: tensorflow-base
    script: build_pkg.sh  # [not win]
    script: build_pkg.bat  # [win]
    build:
      entry_points:
        - toco_from_protos = tensorflow.lite.toco.python.toco_from_protos:main
        - tflite_convert = tensorflow.lite.python.tflite_convert:main
        - toco = tensorflow.lite.python.tflite_convert:main
        - saved_model_cli = tensorflow.python.tools.saved_model_cli:main
        # The tensorboard package adds this entry point.
        # - tensorboard = tensorboard.main:run_main
        - tf_upgrade_v2 = tensorflow.tools.compatibility.tf_upgrade_v2_main:main
        - estimator_ckpt_converter = tensorflow_estimator.python.estimator.tools.checkpoint_converter:main
    requirements:
      # build requirements needs to pick up the compiler run_exports
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        # conda build requirements
        - python
        - pip
        # TF_SYSTEM_LIBS
        - astor >=0.7.1
        - cython >=0.28.4
        - dill >=0.3.1.1
        - giflib
        - grpc-cpp
        - flatbuffers
        - icu
        - jpeg
        - libcurl
        - libpng
        - libprotobuf
        - openssl
        - pybind11
        - snappy
        - sqlite
        - zlib
        # requirements specified by the package itself
        - absl-py >=0.10.0
        - astunparse >=1.6.3
        - python-flatbuffers 1.12.*
        - google-pasta >=0.2
        - h5py 2.10.*
        - keras-preprocessing >=1.1.2
        - numpy 1.19.*
        - opt_einsum 3.3.0.*
        - protobuf >=3.9.2
        - six 1.15.0.*
        - termcolor >=1.1.0
        - typing_extensions 3.7.4.*
        - wheel >=0.35
        - wrapt >=1.11.1
        # upstream wants exact pin for gast
        - gast ==0.3.3
        # TF-API needs to move in sync
        - tensorboard >=2.4.0,<2.5
        - tensorflow-estimator >=2.4.0,<2.5
      run:
        - python
        - absl-py >=0.10.0
        - astunparse >=1.6.3
        - python-flatbuffers 1.12.*
        - google-pasta >=0.2
        - h5py 2.10.*
        - keras-preprocessing >=1.1.2
        - numpy >=1.19
        - opt_einsum 3.3.0.*
        - protobuf >=3.9.2
        - six 1.15.0.*
        - termcolor >=1.1.0
        - typing_extensions 3.7.4.*
        - wheel >=0.35
        - wrapt >=1.11.1
        - grpcio {{ grpc_cpp }}.*
        # upstream wants exact pin for gast
        - gast ==0.3.3
        # TF-API needs to move in sync
        - tensorboard >=2.4.0,<2.5
        - tensorflow-estimator >=2.4.0,<2.5
    test:
      requires:
        - pip
      imports:
        - tensorflow
      commands:
        - pip check
        - tf_upgrade_v2 --help
        - saved_model_cli --help
        - tflite_convert --help     # [not win]
        - toco_from_protos --help   # [not win]
        - toco --help               # [not win]

  - name: tensorflow
    requirements:
      host:
        - python
        - {{ pin_subpackage('tensorflow-base', exact=True) }}
      run:
        - python
        - {{ pin_subpackage('tensorflow-base', exact=True) }}

  - name: libtensorflow
    script: cp_libtensorflow.sh
    build:
      skip: true  # [not linux]
    requirements:
      # build requirements needs to pick up the compiler run_exports
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      # host requirements to pick up run_exports
      host:
        - giflib
        - grpc-cpp
        - icu
        - jpeg
        - libcurl
        - libpng
        - libprotobuf
        - openssl
        - snappy
        - sqlite
        - zlib

    test:
      files:
        - test_libtensorflow.sh
        - test_c.c
      requires:
        - {{ compiler('c') }}
      commands:
        - test -f $PREFIX/lib/libtensorflow.so  # [not win]
        - ./test_libtensorflow.sh               # [not win]

  - name: libtensorflow_cc
    script: cp_libtensorflow_cc.sh
    build:
      skip: true  # [not linux]
    requirements:
      # build requirements needs to pick up the compiler run_exports
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - rsync
      # host requirements to pick up run_exports
      host:
        - giflib
        - grpc-cpp
        - icu
        - jpeg
        - libcurl
        - libpng
        - libprotobuf
        - openssl
        - snappy
        - sqlite
        - zlib
    test:
      files:
        - test_libtensorflow_cc.sh
        - test_cc.cc
      requires:
        - {{ compiler('cxx') }}
      commands:
        - test -f $PREFIX/lib/libtensorflow_cc.so  # [not win]
        - ./test_libtensorflow_cc.sh               # [not win]

about:
  home: http://tensorflow.org/
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: TensorFlow is an open source machine learning framework for everyone.
  description: |
    TensorFlow provides multiple APIs.The lowest level API, TensorFlow Core
    provides you with complete programming control.
    Base package contains only tensorflow, not tensorflow-tensorboard.
  dev_url: https://github.com/tensorflow/tensorflow
  doc_url: https://www.tensorflow.org/get_started/get_started
  doc_source_url: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/docs_src

extra:
  feedstock-name: tensorflow
  recipe-maintainers:
    - farhantejani
    - ghego
    - gilbertfrancois
    - h-vetinari
    - hajapy
    - jschueller
    - njzjz
    - waitingkuo
    - xhochy
