{% set version = "2.6.0" %}

package:
  name: tensorflow-split
  version: {{ version }}

source:
  - url: https://github.com/tensorflow/tensorflow/archive/v{{ version }}.tar.gz
    sha256: 41b32eeaddcbc02b0583660bcf508469550e4cd0f86b22d2abe72dfebeacde0f
    patches:
      - patches/0001-relax-tolerence-in-special_math_test.patch
      - patches/0002-skip-read-only-debugger_cli_common-test.patch
      - patches/0003-relax-precision-in-matrix_log_op_test.patch
      # requires setting GRPCIO_VERSION in build script
      - patches/0004-loosen-requirements.patch
      - patches/0005-remove_deprecated_use_of_error_message.patch
      - patches/0006-protobuf_3_18_comaptibility.patch
      - patches/51450-Fix_protobuf_errors_when_using_system_protobuf.patch
  - url: https://github.com/tensorflow/estimator/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 947705c60c50da0b4a8ceec1bc058aaf6bf567a7efdcd50d5173ebf6bafcf30f
    folder: tensorflow-estimator

build:
  number: 3
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy 1.19.*                           # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}                 # [cuda_compiler_version != "None"]
    - bazel
    - bazel >=4.2.1  # [osx and arm64]
    - grpc-cpp
    - libprotobuf
    - nasm
    - sed
    - rsync  # [linux]
    # realpath is not available from the docker image for cuda <= 10.2
    # so we install coreutils here
    - coreutils  # [cuda_compiler_version != "None"]
  host:
    # GPU requirements for CUDA
    - cudnn      # [cuda_compiler_version != "None"]
    - nccl       # [cuda_compiler_version != "None"]
    # conda build requirements
    - python
    - pip
    - zlib
    - libpng
    - libcurl
    - curl         # [win]
    - unzip        # [not win]
    - zip          # [not win]
    - m2-unzip     # [win]
    - m2-zip       # [win]
    - openjdk >=8
    - nsync
    # TF_SYSTEM_LIBS
    - astor >=0.7.1
    - cython >=0.28.4
    - dill >=0.3.1.1
    - giflib
    - grpc-cpp
    - flatbuffers
    - icu
    - jpeg
    - libpng
    - libprotobuf
    - openssl
    - pybind11
    - sqlite
    - snappy
    - zlib
    # requirements specified by the package itself, see
    # github.com/tensorflow/tensorflow/blob/v{{ version }}/tensorflow/tools/pip_package/setup.py
    - absl-py >=0.10,<1
    - astunparse >=1.6.3,<1.7
    - python-flatbuffers >=1.12,<2
    - google-pasta >=0.2,<1
    - h5py >=3.1.0,<3.2
    - keras-preprocessing >=1.1.2,<1.2
    - numpy 1.19.*
    - opt_einsum >=3.3,<3.4
    - protobuf >=3.9.2
    - six >=1.15,<1.16
    - termcolor >=1.1,<1.2
    - typing_extensions >=3.7.4,<3.8
    - wheel >=0.35,<1
    - wrapt >=1.12.1,<1.13
    # upstream wants exact pin for gast
    - gast ==0.4.0
    # TF-API needs to move in sync
    - tensorboard >=2.6,<3
    - keras >=2.6,<3

outputs:
  - name: tensorflow-base
    script: build_pkg.sh  # [not win]
    script: build_pkg.bat  # [win]
    build:
      string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
      string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
      entry_points:
        - toco_from_protos = tensorflow.lite.toco.python.toco_from_protos:main
        - tflite_convert = tensorflow.lite.python.tflite_convert:main
        - toco = tensorflow.lite.python.tflite_convert:main
        - saved_model_cli = tensorflow.python.tools.saved_model_cli:main
        # The tensorboard package adds this entry point.
        # - tensorboard = tensorboard.main:run_main
        - tf_upgrade_v2 = tensorflow.tools.compatibility.tf_upgrade_v2_main:main
        - estimator_ckpt_converter = tensorflow_estimator.python.estimator.tools.checkpoint_converter:main
    requirements:
      # build requirements needs to pick up the compiler run_exports
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
      host:
        # GPU reuqirements
        - cudnn                   # [cuda_compiler_version != "None"]
        - nccl                    # [cuda_compiler_version != "None"]
        # conda build requirements
        - python
        - pip
        # TF_SYSTEM_LIBS
        - astor >=0.7.1
        - cython >=0.28.4
        - dill >=0.3.1.1
        - giflib
        - grpc-cpp
        - flatbuffers
        - icu
        - jpeg
        - libcurl
        - libpng
        - libprotobuf
        - openssl
        - pybind11
        - snappy
        - sqlite
        - zlib
        # requirements specified by the package itself
        - absl-py >=0.10,<1
        - astunparse >=1.6.3,<1.7
        - python-flatbuffers >=1.12,<2
        - google-pasta >=0.2,<1
        - h5py >=3.1.0,<3.2
        - keras-preprocessing >=1.1.2,<1.2
        - numpy >=1.19.2,<1.20
        - opt_einsum >=3.3,<3.4
        - protobuf >=3.9.2
        - six >=1.15,<1.16
        - termcolor >=1.1,<1.2
        - typing_extensions >=3.7.4,<3.8
        - wheel >=0.35,<1
        - wrapt >=1.12.1,<1.13
        # upstream wants exact pin for gast
        - gast ==0.4.0
        # TF-API needs to move in sync
        - tensorboard >=2.6,<3
        - keras >=2.6,<3
      run:
        - python
        - absl-py >=0.10,<1
        - astunparse >=1.6.3,<1.7
        - python-flatbuffers >=1.12,<2
        - google-pasta >=0.2,<1
        - h5py >=3.1.0,<3.2
        - keras-preprocessing >=1.1.2,<1.2
        - numpy >=1.19.2,<1.20
        - opt_einsum >=3.3,<3.4
        - protobuf >=3.9.2
        - six >=1.15,<1.16
        - termcolor >=1.1,<1.2
        - typing_extensions >=3.7.4,<3.8
        - wheel >=0.35,<1
        - wrapt >=1.12.1,<1.13
        # upstream wants exact pin for gast
        - gast ==0.4.0
        # TF-API needs to move in sync
        - tensorboard >=2.6,<3
        - keras >=2.6,<3
        - grpcio {{ grpc_cpp }}.*
    test:
      files:
        - test_tensorflow_base.py
      commands:
        - cat test_tensorflow_base.py   # [unix]
        - python test_tensorflow_base.py
        - tf_upgrade_v2 --help
        - saved_model_cli --help
        - tflite_convert --help     # [not win]
        - toco_from_protos --help   # [not win]
        - toco --help               # [not win]

  - name: tensorflow-estimator
    script: build_estimator.sh   # [not win]
    script: build_estimator.bat  # [win]
    build:
      string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
      string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        # Keep the cuda compiler here since it helps package solvers
        # decide on the cuda variant
        # https://github.com/conda-forge/tensorflow-feedstock/issues/162
        - {{ compiler('cuda') }}                 # [cuda_compiler_version != "None"]
        - bazel
        - bazel >=4.2.1  # [osx and arm64]
      host:
        - python
        - pip
        - setuptools
        - wheel
        # This ensures that a consistent version of openssl is chosen between
        # all packages.
        # https://github.com/conda-forge/conda-forge.github.io/issues/1528
        - openssl
        - {{ pin_subpackage('tensorflow-base', exact=True) }}
      run:
        - python
        - {{ pin_subpackage('tensorflow-base', exact=True) }}
    test:
      requires:
        - pip
      commands:
        - pip check


  - name: tensorflow
    build:
      string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
      string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]

      # weigh down cpu implementation and give cuda preference
      track_features:
        - tensorflow-cpu          # [cuda_compiler_version == "None"]

    requirements:
      build:
        # Keep the other compilers here so as to help solve for the
        # required version of libc
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        # Keep the cuda compiler here since it helps package solvers
        # decide on the cuda variant
        # https://github.com/conda-forge/tensorflow-feedstock/issues/162
        - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
      host:
        - python
        # This ensures that a consistent version of openssl is chosen between
        # all packages.
        # https://github.com/conda-forge/conda-forge.github.io/issues/1528
        - openssl
        - {{ pin_subpackage('tensorflow-base', exact=True) }}
      run:
        - python
        - {{ pin_subpackage('tensorflow-estimator', exact=True) }}
        - {{ pin_subpackage('tensorflow-base', exact=True) }}
    test:
      requires:
        - pip
      imports:
        - tensorflow
      commands:
        - pip check

  - name: libtensorflow
    script: cp_libtensorflow.sh
    build:
      skip: true  # [not linux]
      string: cuda{{ cuda_compiler_version | replace('.', '') }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
      string: cpu_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
    requirements:
      # build requirements needs to pick up the compiler run_exports
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        # Keep the cuda compiler here since it helps package solvers
        # decide on the cuda variant
        # https://github.com/conda-forge/tensorflow-feedstock/issues/162
        - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
      # host requirements to pick up run_exports
      host:
        - giflib
        - grpc-cpp
        - icu
        - jpeg
        - libcurl
        - libpng
        - libprotobuf
        - openssl
        - snappy
        - sqlite
        - zlib

    test:
      files:
        - test_libtensorflow.sh
        - test_c.c
      requires:
        - {{ compiler('c') }}
      commands:
        - test -f $PREFIX/lib/libtensorflow.so  # [not win and cuda_compiler_version == "None"]
        - ./test_libtensorflow.sh               # [not win and cuda_compiler_version == "None"]

  - name: libtensorflow_cc
    script: cp_libtensorflow_cc.sh
    build:
      skip: true  # [not linux]
      string: cuda{{ cuda_compiler_version | replace('.', '') }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
      string: cpu_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
    requirements:
      # build requirements needs to pick up the compiler run_exports
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        # Keep the cuda compiler here since it helps package solvers
        # decide on the cuda variant
        # https://github.com/conda-forge/tensorflow-feedstock/issues/162
        - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
      # host requirements to pick up run_exports
      host:
        - giflib
        - grpc-cpp
        - icu
        - jpeg
        - libcurl
        - libpng
        - libprotobuf
        - openssl
        - snappy
        - sqlite
        - zlib
    test:
      files:
        - test_libtensorflow_cc.sh
        - test_cc.cc
      requires:
        - {{ compiler('cxx') }}
      commands:
        - test -f $PREFIX/lib/libtensorflow_cc.so  # [not win and cuda_compiler_version == "None"]
        - ./test_libtensorflow_cc.sh               # [not win and cuda_compiler_version == "None"]

  # 2021/08/01, hmaarrfk
  # While this seems like a roundabout way of defining the package name
  # It helps the linter avoid errors on a package not having tests.
  {% set tensorflow_cpu_gpu = "tensorflow-cpu" %}   # [cuda_compiler_version == "None" or cuda_compiler_version is undefined]
  {% set tensorflow_cpu_gpu = "tensorflow-gpu" %}   # [cuda_compiler_version != "None"]
  - name: {{ tensorflow_cpu_gpu }}
    build:
      string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
      string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}                                      # [cuda_compiler_version == "None"]
      detect_binary_files_with_prefix: False
    requirements:
      run:
        - {{ pin_subpackage("tensorflow", exact=True) }}
    test:
      imports:
        - tensorflow

about:
  home: http://tensorflow.org/
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: TensorFlow is an open source machine learning framework for everyone.
  description: |
    TensorFlow provides multiple APIs.The lowest level API, TensorFlow Core
    provides you with complete programming control.
    Base package contains only tensorflow, not tensorflow-tensorboard.
  dev_url: https://github.com/tensorflow/tensorflow
  doc_url: https://www.tensorflow.org/get_started/get_started
  doc_source_url: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/docs_src

extra:
  feedstock-name: tensorflow
  recipe-maintainers:
    - farhantejani
    - ghego
    - gilbertfrancois
    - h-vetinari
    - hajapy
    - jschueller
    - njzjz
    - waitingkuo
    - xhochy
    - hmaarrfk
    - wolfv
